import { View, Text, StyleSheet } from "@react-pdf/renderer";
import type { ReportData } from "@/types/report";
import ReportPage from "./ReportPage";
import { colors, fontSize, baseStyles, formatReportDate } from "./styles";

const s = StyleSheet.create({
  term: {
    fontSize: fontSize.body,
    fontFamily: "Helvetica-Bold",
    color: colors.textPrimary,
    marginBottom: 2,
  },
  explanation: {
    fontSize: fontSize.body,
    color: colors.textSecondary,
    lineHeight: 1.5,
    marginBottom: 10,
  },
  disclaimerText: {
    fontSize: fontSize.body,
    color: colors.textMuted,
    lineHeight: 1.6,
    fontStyle: "italic",
  },
  metaBox: {
    backgroundColor: colors.surface,
    borderRadius: 6,
    borderWidth: 0.5,
    borderColor: colors.border,
    padding: 12,
    marginTop: 20,
  },
  metaLine: {
    fontSize: fontSize.caption,
    color: colors.textMuted,
    marginBottom: 2,
  },
});

export default function ReportFooterPage({ data }: { data: ReportData }) {
  const { deepDive } = data;

  return (
    <ReportPage ticker={data.ticker} generatedAt={data.generatedAt}>
      {/* Educational Notes */}
      {deepDive.educational_notes.length > 0 && (
        <View style={baseStyles.section}>
          <Text style={baseStyles.h1}>Learn More</Text>
          {deepDive.educational_notes.map((note, i) => (
            <View key={i}>
              <Text style={s.term}>{note.term}</Text>
              <Text style={s.explanation}>{note.explanation}</Text>
            </View>
          ))}
        </View>
      )}

      <View style={baseStyles.separator} />

      {/* Disclaimer */}
      <View style={baseStyles.section}>
        <Text style={baseStyles.h1}>Disclaimer</Text>
        <Text style={s.disclaimerText}>{deepDive.disclaimer}</Text>
      </View>

      {/* Generation Metadata */}
      <View style={s.metaBox}>
        <Text style={s.metaLine}>Report generated by Options Dashboard</Text>
        <Text style={s.metaLine}>Analysis engine: OpenRouter (Qwen3.5+)</Text>
        <Text style={s.metaLine}>Market data: Yahoo Finance</Text>
        <Text style={s.metaLine}>Chart library: Lightweight Charts v5</Text>
        <Text style={s.metaLine}>
          Date: {formatReportDate(data.generatedAt)}
        </Text>
      </View>
    </ReportPage>
  );
}
